### ISSUE TITLE
(openbsd) build issues

### ISSUE THREAD

**Issue by qbit** [letoram/arcan#125]
```
[  8%] Building C object shmif/CMakeFiles/arcan_shmif_int.dir/__/platform/posix/time.c.o
/home/qbit/dev/arcan/src/platform/posix/time.c:19:16: error: use of undeclared identifier
      'CLOCK_REALTIME_FAST'
        clock_gettime(CLOCK_MONOTONIC_RAW, &tp);
                      ^
<command line>:1:29: note: expanded from here
#define CLOCK_MONOTONIC_RAW CLOCK_REALTIME_FAST
                            ^
1 error generated.
*** Error 1 in . (shmif/CMakeFiles/arcan_shmif_int.dir/build.make:163 'shmif/CMakeFiles/arcan_shmif_int.dir/__/platform/posix/time.c.o': cd ...)
*** Error 1 in . (CMakeFiles/Makefile2:226 'shmif/CMakeFiles/arcan_shmif_int.dir/all')
*** Error 1 in /home/qbit/dev/arcan/build (Makefile:128 'all')
```

**Comment by letoram** [comment]
I havn't gotten around to port to OpenBSD yet - it's on the todo list (I want pledge!) but other priorities are in the way. It's possible that you can get around it with CLOCK_MONOTONIC_RAW -> CLOCK_MONTONIC (that one is POSIX, but edge conditions with NTP). afaik the event/input layer in OBSD is different from both evdev and the fbsd one so that needs a freshly written one :/

**Comment by letoram** [comment]
Initial bringup signs of life:
https://github.com/letoram/arcan/commit/7d8313fb8229fc9586394b05a792618494e09338

**Comment by letoram** [comment]
The issue should be corrected so closing this one, further progress/tracking in #126
