### ISSUE TITLE
Input devices are detected wrong

### ISSUE THREAD

**Issue by icecream95** [letoram/arcan#198]
On my system (an armv7l chromebook running Void Linux with elogind), the input devices are detected wrong.

When running `arcan console` from a TTY with arcan compiled from latest master (c672275), the keyboard does not work, and the touchpad is detected as a touchscreen—I had to spend 15 minutes trying to tap it in the right places to quit Arcan using the virtual keyboard.

**Comment by letoram** [comment]
A source of contention as udev/dbus is blacklisted. The way input detection works is that it monitors a folder for input devices (/dev/input by default) through inotify (l. If it appears there, it grabs it -- if permitted. It might be that elogind just sits and holds a lock on the keyboard.

If arcan is suid, it privseps into two processes, one that acts as a logind- like device handler (VT switching and so on).
The compromise is that there are ways of setting up external input drivers, launched with:

    -H hooks/external_input.lua console

Has it expose extio_1 for custom input drivers.

    ARCAN_CONNPATH=extio_1 logind_friendly_driver

The crux is that the arcan-devices github repo still doesn't have a libinput based external driver. It might/should eventually, but it's low on my list since well, never systemd.

**Comment by letoram** [comment]
The easier way to test your input stack without being burned like this is:

    arcan /path/to/tests/interactive/eventtest

It will print events from the devices it receives, and shut down after a while of no (digital) input. A debug build will also be quite verbose in the output (redirect to a file since the tty switches to graphics mode) about what happens with the input devices.

**Comment by icecream95** [comment]
Running eventtest prints:

```
(eventtest) status(5240)   mouse, cros ec, added
```

so it seems like it thinks the keyboard is a mouse.

Press and release events from the keyboard do appear in the 'Digital' pane, but there is nothing in the other panes.

Touchpad movements are shown in the "Touch" pane, with the coordinates in that pane being the absolute position on the touchpad.

**Comment by letoram** [comment]
So the classifier goes 'anything starts as a catch-all game device' -> 'does the button count / axis count etc. resemble a mouse?, then mouse' -> 'keyboard as last resort'. There is a hack path to force a specific classifier (use evtest to grab the label and patch into the table in src/platform/evdev/device_db.h).

The plan was to use the config system (arcan_db add_appl_kv arcan evdev_map keyboard "My Weird Thing") and a helper script for probing your local setup, but still 'todo'.

**Comment by letoram** [comment]
something like this was added (and fairly untested) - see commit 636b31f75
